// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfSFM_38TRychUydMHbKXxgsbMWMAYI8',
    appId: '1:864170297938:web:69ca9a0c55917d234ead8b',
    messagingSenderId: '864170297938',
    projectId: 'garoceryauth',
    authDomain: 'garoceryauth.firebaseapp.com',
    storageBucket: 'garoceryauth.firebasestorage.app',
    measurementId: 'G-VFRC4HV35M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5HAaQQKnsxBGgCIP26pO4K1g7j_dSI0',
    appId: '1:864170297938:android:3625584f5ec7e4884ead8b',
    messagingSenderId: '864170297938',
    projectId: 'garoceryauth',
    storageBucket: 'garoceryauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01QDxToCyWL0jAdizHd5ebOVZeAZuh7Y',
    appId: '1:864170297938:ios:a111481437cd8d234ead8b',
    messagingSenderId: '864170297938',
    projectId: 'garoceryauth',
    storageBucket: 'garoceryauth.firebasestorage.app',
    androidClientId: '864170297938-hniuqukf9cc5p6vifn1v8118ep953nef.apps.googleusercontent.com',
    iosClientId: '864170297938-8mubrrao2ak6piqjsa55vju75inu8vsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.garoceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01QDxToCyWL0jAdizHd5ebOVZeAZuh7Y',
    appId: '1:864170297938:ios:a111481437cd8d234ead8b',
    messagingSenderId: '864170297938',
    projectId: 'garoceryauth',
    storageBucket: 'garoceryauth.firebasestorage.app',
    androidClientId: '864170297938-hniuqukf9cc5p6vifn1v8118ep953nef.apps.googleusercontent.com',
    iosClientId: '864170297938-8mubrrao2ak6piqjsa55vju75inu8vsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.garoceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTfSFM_38TRychUydMHbKXxgsbMWMAYI8',
    appId: '1:864170297938:web:72550bb3b284d8c94ead8b',
    messagingSenderId: '864170297938',
    projectId: 'garoceryauth',
    authDomain: 'garoceryauth.firebaseapp.com',
    storageBucket: 'garoceryauth.firebasestorage.app',
    measurementId: 'G-VQF74DY7MR',
  );
}
